// ============================================================
// Auto-generated by SignLanguage Unity Exporter
// ============================================================
// 将此脚本挂载到场景中的 Animator 所在的 GameObject 上。
// 确保场景中有一个 Humanoid Avatar，且设置正确。
//
// 使用方法:
//   1. 将 JSON 动画文件放入 Resources/ 或 StreamingAssets/ 目录
//   2. 调用 PlayAnimation() 开始播放
//   3. 可选: 通过 AnimationFinished 事件监听播放完成
// ============================================================

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 运行时手语动画播放器。
/// 从 JSON 中读取 MediaPipe 关键点导出的骨骼姿态数据，
/// 通过 HumanBodyBones 驱动 Humanoid Avatar。
/// </summary>
public class SignLanguagePlayer_sample_用药 : MonoBehaviour
{
    [Header("动画数据")]
    [Tooltip("可选：直接把 JSON 拖入此框（文件须位于 Assets 目录下被 Unity 导入，StreamingAssets 内的文件无法拖入）。非空时优先使用它。")]
    public TextAsset animationJson;
    [Tooltip("JSON动画文件路径 (相对于 StreamingAssets 或 Resources)，上方未拖入时使用")]
    public string animationJsonPath = "unity_animations/sample_用药_unity_anim.json";

    [Header("播放设置")]
    [Tooltip("是否在 Start 时自动播放")]
    public bool playOnStart = false;
    [Tooltip("是否循环播放")]
    public bool loop = false;
    [Tooltip("播放速度倍率")]
    [Range(0.1f, 5f)]
    public float speed = 1f;

    [Header("平滑设置")]
    [Tooltip("是否启用骨骼平滑（减少抖动）")]
    public bool enableSmoothing = true;
    [Tooltip("平滑因子 (0=无平滑, 1=完全滞后)")]
    [Range(0f, 1f)]
    public float smoothFactor = 0.3f;

    [Header("位置")]
    [Tooltip("骨骼位置整体偏移（用于把角色的脚对齐到地面）。导出坐标原点在双肩中点、单位为米，通常需向下偏移约1米。")]
    public Vector3 positionOffset = Vector3.zero;

    [Header("物理")]
    [Tooltip("在骨骼动作同步后再启用布料/头发物理，避免穿模或僵硬")]
    public bool enablePhysicsAfterSync = true;

    [Header("调试")]
    [Tooltip("在 Scene 视图中绘制骨骼调试线")]
    public bool drawDebugBones = false;

    // 事件
    public event Action OnAnimationFinished;

    // 内部状态
    private Animator _animator;
    private UnityAnimationData _animData;
    private Dictionary<string, Transform> _boneCache = new Dictionary<string, Transform>();
    private Dictionary<string, Vector3> _boneRestPositions = new Dictionary<string, Vector3>();
    private Dictionary<string, Quaternion> _boneRestRotations = new Dictionary<string, Quaternion>();
    private bool _isPlaying = false;
    private bool _isInitialized = false;
    private float _playbackTime = 0f;
    private float _animDuration = 0f;
    private int _currentFrameIndex = -1;

    // 物理（布料/头发）
    private Cloth[] _cloths;
    private bool _physicsEnabled = false;

    // 骨骼映射: JSON中骨骼名 → HumanBodyBones
    private static readonly Dictionary<string, HumanBodyBones> BoneNameToEnum = new Dictionary<string, HumanBodyBones>
    {
        // 身体
        { "Hips", HumanBodyBones.Hips },
        { "Spine", HumanBodyBones.Spine },
        { "Chest", HumanBodyBones.Chest },
        { "UpperChest", HumanBodyBones.UpperChest },
        { "Neck", HumanBodyBones.Neck },
        { "Head", HumanBodyBones.Head },
        // 手臂
        { "LeftShoulder", HumanBodyBones.LeftShoulder },
        { "LeftUpperArm", HumanBodyBones.LeftUpperArm },
        { "LeftLowerArm", HumanBodyBones.LeftLowerArm },
        { "LeftHand", HumanBodyBones.LeftHand },
        { "RightShoulder", HumanBodyBones.RightShoulder },
        { "RightUpperArm", HumanBodyBones.RightUpperArm },
        { "RightLowerArm", HumanBodyBones.RightLowerArm },
        { "RightHand", HumanBodyBones.RightHand },
        // 腿
        { "LeftUpperLeg", HumanBodyBones.LeftUpperLeg },
        { "LeftLowerLeg", HumanBodyBones.LeftLowerLeg },
        { "LeftFoot", HumanBodyBones.LeftFoot },
        { "LeftToes", HumanBodyBones.LeftToes },
        { "RightUpperLeg", HumanBodyBones.RightUpperLeg },
        { "RightLowerLeg", HumanBodyBones.RightLowerLeg },
        { "RightFoot", HumanBodyBones.RightFoot },
        { "RightToes", HumanBodyBones.RightToes },
        // 左手手指
        { "LeftThumbProximal", HumanBodyBones.LeftThumbProximal },
        { "LeftThumbIntermediate", HumanBodyBones.LeftThumbIntermediate },
        { "LeftThumbDistal", HumanBodyBones.LeftThumbDistal },
        { "LeftIndexProximal", HumanBodyBones.LeftIndexProximal },
        { "LeftIndexIntermediate", HumanBodyBones.LeftIndexIntermediate },
        { "LeftIndexDistal", HumanBodyBones.LeftIndexDistal },
        { "LeftMiddleProximal", HumanBodyBones.LeftMiddleProximal },
        { "LeftMiddleIntermediate", HumanBodyBones.LeftMiddleIntermediate },
        { "LeftMiddleDistal", HumanBodyBones.LeftMiddleDistal },
        { "LeftRingProximal", HumanBodyBones.LeftRingProximal },
        { "LeftRingIntermediate", HumanBodyBones.LeftRingIntermediate },
        { "LeftRingDistal", HumanBodyBones.LeftRingDistal },
        { "LeftLittleProximal", HumanBodyBones.LeftLittleProximal },
        { "LeftLittleIntermediate", HumanBodyBones.LeftLittleIntermediate },
        { "LeftLittleDistal", HumanBodyBones.LeftLittleDistal },
        // 右手手指
        { "RightThumbProximal", HumanBodyBones.RightThumbProximal },
        { "RightThumbIntermediate", HumanBodyBones.RightThumbIntermediate },
        { "RightThumbDistal", HumanBodyBones.RightThumbDistal },
        { "RightIndexProximal", HumanBodyBones.RightIndexProximal },
        { "RightIndexIntermediate", HumanBodyBones.RightIndexIntermediate },
        { "RightIndexDistal", HumanBodyBones.RightIndexDistal },
        { "RightMiddleProximal", HumanBodyBones.RightMiddleProximal },
        { "RightMiddleIntermediate", HumanBodyBones.RightMiddleIntermediate },
        { "RightMiddleDistal", HumanBodyBones.RightMiddleDistal },
        { "RightRingProximal", HumanBodyBones.RightRingProximal },
        { "RightRingIntermediate", HumanBodyBones.RightRingIntermediate },
        { "RightRingDistal", HumanBodyBones.RightRingDistal },
        { "RightLittleProximal", HumanBodyBones.RightLittleProximal },
        { "RightLittleIntermediate", HumanBodyBones.RightLittleIntermediate },
        { "RightLittleDistal", HumanBodyBones.RightLittleDistal },
    };

    // 骨骼 → 子骨骼（用于计算"指向方向"）。
    // 手指 Distal 的"子"是合成 Tip 关节（无对应 Transform，rest 方向用骨骼自身 +Y 轴）。
    private static readonly Dictionary<string, string> BoneChild = new Dictionary<string, string>
    {
        // 躯干/头
        { "Hips", "Spine" },
        { "Spine", "Chest" },
        { "Chest", "UpperChest" },
        { "UpperChest", "Neck" },
        { "Neck", "Head" },
        // 手臂
        { "LeftShoulder", "LeftUpperArm" },
        { "LeftUpperArm", "LeftLowerArm" },
        { "LeftLowerArm", "LeftHand" },
        { "RightShoulder", "RightUpperArm" },
        { "RightUpperArm", "RightLowerArm" },
        { "RightLowerArm", "RightHand" },
        // 腿
        { "LeftUpperLeg", "LeftLowerLeg" },
        { "LeftLowerLeg", "LeftFoot" },
        { "LeftFoot", "LeftToes" },
        { "RightUpperLeg", "RightLowerLeg" },
        { "RightLowerLeg", "RightFoot" },
        { "RightFoot", "RightToes" },
        // 手掌 → 中指基关节（决定掌心朝向）
        { "LeftHand", "LeftMiddleProximal" },
        { "RightHand", "RightMiddleProximal" },
        // 左手手指
        { "LeftThumbProximal", "LeftThumbIntermediate" },
        { "LeftThumbIntermediate", "LeftThumbDistal" },
        { "LeftThumbDistal", "LeftThumbTip" },
        { "LeftIndexProximal", "LeftIndexIntermediate" },
        { "LeftIndexIntermediate", "LeftIndexDistal" },
        { "LeftIndexDistal", "LeftIndexTip" },
        { "LeftMiddleProximal", "LeftMiddleIntermediate" },
        { "LeftMiddleIntermediate", "LeftMiddleDistal" },
        { "LeftMiddleDistal", "LeftMiddleTip" },
        { "LeftRingProximal", "LeftRingIntermediate" },
        { "LeftRingIntermediate", "LeftRingDistal" },
        { "LeftRingDistal", "LeftRingTip" },
        { "LeftLittleProximal", "LeftLittleIntermediate" },
        { "LeftLittleIntermediate", "LeftLittleDistal" },
        { "LeftLittleDistal", "LeftLittleTip" },
        // 右手手指
        { "RightThumbProximal", "RightThumbIntermediate" },
        { "RightThumbIntermediate", "RightThumbDistal" },
        { "RightThumbDistal", "RightThumbTip" },
        { "RightIndexProximal", "RightIndexIntermediate" },
        { "RightIndexIntermediate", "RightIndexDistal" },
        { "RightIndexDistal", "RightIndexTip" },
        { "RightMiddleProximal", "RightMiddleIntermediate" },
        { "RightMiddleIntermediate", "RightMiddleDistal" },
        { "RightMiddleDistal", "RightMiddleTip" },
        { "RightRingProximal", "RightRingIntermediate" },
        { "RightRingIntermediate", "RightRingDistal" },
        { "RightRingDistal", "RightRingTip" },
        { "RightLittleProximal", "RightLittleIntermediate" },
        { "RightLittleIntermediate", "RightLittleDistal" },
        { "RightLittleDistal", "RightLittleTip" },
    };

    // 自上而下的应用顺序（父先于子，Unity 才能正确换算 localRotation）
    private static readonly string[] TopDownOrder = new string[]
    {
        "Hips", "Spine", "Chest", "UpperChest", "Neck", "Head",
        "LeftShoulder", "LeftUpperArm", "LeftLowerArm", "LeftHand",
        "LeftThumbProximal", "LeftThumbIntermediate", "LeftThumbDistal",
        "LeftIndexProximal", "LeftIndexIntermediate", "LeftIndexDistal",
        "LeftMiddleProximal", "LeftMiddleIntermediate", "LeftMiddleDistal",
        "LeftRingProximal", "LeftRingIntermediate", "LeftRingDistal",
        "LeftLittleProximal", "LeftLittleIntermediate", "LeftLittleDistal",
        "RightShoulder", "RightUpperArm", "RightLowerArm", "RightHand",
        "RightThumbProximal", "RightThumbIntermediate", "RightThumbDistal",
        "RightIndexProximal", "RightIndexIntermediate", "RightIndexDistal",
        "RightMiddleProximal", "RightMiddleIntermediate", "RightMiddleDistal",
        "RightRingProximal", "RightRingIntermediate", "RightRingDistal",
        "RightLittleProximal", "RightLittleIntermediate", "RightLittleDistal",
        "LeftUpperLeg", "LeftLowerLeg", "LeftFoot", "LeftToes",
        "RightUpperLeg", "RightLowerLeg", "RightFoot", "RightToes",
    };

    void Start()
    {
        if (playOnStart)
            InitializeAndPlay();
    }

    void Update()
    {
        if (!_isPlaying || _animData == null) return;

        _playbackTime += Time.deltaTime * speed;

        if (_playbackTime >= _animDuration)
        {
            if (loop)
            {
                _playbackTime = 0f;
                _currentFrameIndex = -1;
            }
            else
            {
                _isPlaying = false;
                OnAnimationFinished?.Invoke();
                return;
            }
        }

        ApplyCurrentFrame();
    }

    /// <summary>
    /// 初始化并开始播放
    /// </summary>
    public void InitializeAndPlay()
    {
        if (!Initialize())
        {
            Debug.LogError("[SignLanguagePlayer_sample_用药] 初始化失败！");
            return;
        }
        PlayAnimation();
    }

    /// <summary>
    /// 初始化：加载JSON、缓存骨骼Transform
    /// </summary>
    public bool Initialize()
    {
        _animator = GetComponent<Animator>();
        if (_animator == null)
        {
            Debug.LogError("[SignLanguagePlayer_sample_用药] 未找到 Animator 组件！");
            return false;
        }

        if (!_animator.isHuman)
        {
            Debug.LogError("[SignLanguagePlayer_sample_用药] Avatar 不是 Humanoid 类型！请在 Rig 中设置为 Humanoid。");
            return false;
        }

        // 加载JSON
        string jsonText = LoadJson(animationJsonPath);
        if (string.IsNullOrEmpty(jsonText))
        {
            Debug.LogError($"[SignLanguagePlayer_sample_用药] 无法加载动画JSON: {animationJsonPath}");
            return false;
        }

        _animData = JsonUtility.FromJson<UnityAnimationData>(jsonText);
        if (_animData == null || _animData.frames == null || _animData.frames.Length == 0)
        {
            Debug.LogError("[SignLanguagePlayer_sample_用药] JSON 解析失败或动画数据为空！");
            return false;
        }

        _animDuration = _animData.total_frames / _animData.fps;

        // 缓存骨骼Transform，并记录rest pose
        _boneCache.Clear();
        _boneRestPositions.Clear();
        _boneRestRotations.Clear();

        // 先禁用Animator使其不干扰骨骼驱动
        _animator.enabled = false;

        // 通过bone_registry数组遍历所有骨骼
        if (_animData.bone_registry != null)
        {
            foreach (var entry in _animData.bone_registry)
            {
                if (BoneNameToEnum.TryGetValue(entry.bone_name, out HumanBodyBones bone))
                {
                    Transform t = _animator.GetBoneTransform(bone);
                    if (t != null)
                    {
                        _boneCache[entry.bone_name] = t;
                        _boneRestPositions[entry.bone_name] = t.position;
                        _boneRestRotations[entry.bone_name] = t.rotation;
                    }
                    else
                    {
                        Debug.LogWarning($"[SignLanguagePlayer_sample_用药] 未找到骨骼: {entry.bone_name} ({bone})");
                    }
                }
            }
        }

        Debug.Log($"[SignLanguagePlayer_sample_用药] 初始化完成: {_boneCache.Count} 骨骼, "
                  + $"{_animData.total_frames} 帧, {_animData.fps} FPS, "
                  + $"时长 {_animDuration:F2}s, 词条: {_animData.word}");

        // 物理：初始时禁用布料/头发，待首帧骨骼动作同步后再启用
        if (enablePhysicsAfterSync)
        {
            _cloths = GetComponentsInChildren<Cloth>(true);
            foreach (var c in _cloths) c.enabled = false;
            _physicsEnabled = false;
        }

        _isInitialized = true;
        return true;
    }

    private string LoadJson(string path)
    {
        // 优先使用 Inspector 拖入的 TextAsset 资源
        if (animationJson != null)
            return animationJson.text;

        // 尝试 StreamingAssets
        string fullPath = System.IO.Path.Combine(Application.streamingAssetsPath, path);
        if (System.IO.File.Exists(fullPath))
        {
            if (fullPath.Contains("://"))
            {
                // Android 特殊处理
                using (var www = UnityEngine.Networking.UnityWebRequest.Get(fullPath))
                {
                    var op = www.SendWebRequest();
                    while (!op.isDone) { }
                    return www.downloadHandler.text;
                }
            }
            return System.IO.File.ReadAllText(fullPath);
        }

        // 尝试从 Resources
        var res = Resources.Load<TextAsset>(path.Replace(".json", ""));
        if (res != null)
            return res.text;

        return null;
    }

    /// <summary>
    /// 开始播放动画
    /// </summary>
    public void PlayAnimation()
    {
        if (!_isInitialized)
        {
            Debug.LogError("[SignLanguagePlayer_sample_用药] 未初始化，请先调用 Initialize()！");
            return;
        }

        _playbackTime = 0f;
        _currentFrameIndex = -1;
        _isPlaying = true;
    }

    /// <summary>
    /// 停止播放
    /// </summary>
    public void StopAnimation()
    {
        _isPlaying = false;
        ResetToRestPose();
    }

    /// <summary>
    /// 暂停播放
    /// </summary>
    public void PauseAnimation()
    {
        _isPlaying = false;
    }

    /// <summary>
    /// 恢复播放
    /// </summary>
    public void ResumeAnimation()
    {
        if (_isInitialized)
            _isPlaying = true;
    }

    /// <summary>
    /// 根据当前播放时间应用对应帧的骨骼姿态
    /// </summary>
    private void ApplyCurrentFrame()
    {
        if (_animData == null) return;

        // 找到当前时间对应的帧
        int targetFrameIndex = Mathf.FloorToInt(_playbackTime * _animData.fps);
        targetFrameIndex = Mathf.Clamp(targetFrameIndex, 0, _animData.frames.Length - 1);

        if (targetFrameIndex == _currentFrameIndex) return;
        _currentFrameIndex = targetFrameIndex;

        ApplyFrameDirect(_animData.frames[targetFrameIndex]);
    }

    /// <summary>
    /// 将单帧骨骼姿态应用到骨骼（rest-pose 感知的 FK）。
    /// 用 JSON 里的世界关节位置计算每根骨骼的"指向方向"，再相对角色真实 rest pose 求 delta 旋转，
    /// 从根本上避免"绝对轴旋转"忽略 rest pose 导致的扭曲。
    /// </summary>
    private void ApplyFrameDirect(FrameData frame)
    {
        // 1. 汇总本帧各关节的目标世界位置（导出坐标系，原点=双肩中点，米）
        var jsonPos = new Dictionary<string, Vector3>();
        foreach (var bp in frame.bone_poses)
        {
            if (bp.local_position != null && bp.local_position.Length >= 3)
                jsonPos[bp.bone_name] = new Vector3(bp.local_position[0], bp.local_position[1], bp.local_position[2]);
        }

        // 2. 计算每根骨骼的 delta-from-rest 世界旋转
        var newWorldRot = new Dictionary<string, Quaternion>();
        foreach (var kv in _boneCache)
        {
            string bone = kv.Key;
            if (!BoneChild.TryGetValue(bone, out string child)) continue;
            if (!jsonPos.TryGetValue(bone, out Vector3 selfPos)) continue;
            if (!jsonPos.TryGetValue(child, out Vector3 childPos)) continue;

            Vector3 restDir = RestDirection(bone, child);
            Vector3 targetDir = childPos - selfPos;
            if (restDir.sqrMagnitude < 1e-8f || targetDir.sqrMagnitude < 1e-8f) continue;

            Quaternion delta = Quaternion.FromToRotation(restDir.normalized, targetDir.normalized);
            newWorldRot[bone] = delta * _boneRestRotations[bone];
        }

        // Head 特殊处理：头朝向 = 鼻(Head) - 颈(Neck)
        if (jsonPos.ContainsKey("Head") && jsonPos.ContainsKey("Neck")
            && _boneRestPositions.ContainsKey("Head") && _boneRestPositions.ContainsKey("Neck"))
        {
            Vector3 restDir = _boneRestPositions["Head"] - _boneRestPositions["Neck"];
            Vector3 targetDir = jsonPos["Head"] - jsonPos["Neck"];
            if (restDir.sqrMagnitude > 1e-8f && targetDir.sqrMagnitude > 1e-8f)
                newWorldRot["Head"] = Quaternion.FromToRotation(restDir.normalized, targetDir.normalized) * _boneRestRotations["Head"];
        }

        // 3. 自上而下应用世界旋转（父先于子，Unity 自动换算 localRotation）
        foreach (string bone in TopDownOrder)
        {
            if (!newWorldRot.TryGetValue(bone, out Quaternion rot)) continue;
            if (!_boneCache.TryGetValue(bone, out Transform t)) continue;
            t.rotation = enableSmoothing
                ? Quaternion.Slerp(t.rotation, rot, 1f - smoothFactor)
                : rot;
        }

        // 4. 应用 BlendShape（表情）
        if (frame.blendshapes != null)
        {
            var smr = GetComponent<SkinnedMeshRenderer>();
            if (smr != null)
            {
                foreach (var bs in frame.blendshapes)
                {
                    int index = smr.sharedMesh.GetBlendShapeIndex(bs.name);
                    if (index >= 0)
                    {
                        smr.SetBlendShapeWeight(index, bs.weight);
                    }
                }
            }
        }

        // 5. 物理：首帧骨骼动作同步后，启用布料/头发物理
        if (enablePhysicsAfterSync && !_physicsEnabled)
        {
            if (_cloths == null)
                _cloths = GetComponentsInChildren<Cloth>(true);
            if (_cloths != null)
                foreach (var c in _cloths) c.enabled = true;
            _physicsEnabled = true;
        }
    }

    /// <summary>
    /// 计算骨骼的 rest 指向方向。
    /// 有真实子骨骼时用 rest 位置差；子骨骼是合成 Tip（手指末端）时用骨骼自身 rest 世界旋转的 +Y 轴。
    /// </summary>
    private Vector3 RestDirection(string bone, string child)
    {
        if (_boneRestPositions.ContainsKey(child))
            return _boneRestPositions[child] - _boneRestPositions[bone];
        if (_boneRestRotations.TryGetValue(bone, out Quaternion restRot))
            return restRot * Vector3.up;  // Unity Humanoid 骨骼 +Y 轴沿骨骼指向子关节
        return Vector3.zero;
    }

    /// <summary>
    /// 跳到指定帧并应用（供校验器等外部工具使用，不启动播放循环）
    /// </summary>
    public void ApplyFrameAt(int frameIndex)
    {
        if (_animData == null || _animData.frames == null || _animData.frames.Length == 0)
            return;
        int idx = Mathf.Clamp(frameIndex, 0, _animData.frames.Length - 1);
        _currentFrameIndex = -1;  // 强制重新应用
        ApplyFrameDirect(_animData.frames[idx]);
    }

    /// <summary>
    /// 获取所有关键帧索引（供输出校验使用）
    /// </summary>
    public int[] GetKeyframeIndices()
    {
        if (_animData == null || _animData.frames == null)
            return new int[0];
        var list = new List<int>();
        for (int i = 0; i < _animData.frames.Length; i++)
            if (_animData.frames[i].is_keyframe) list.Add(i);
        if (list.Count == 0) list.Add(0);
        return list.ToArray();
    }

    /// <summary>
    /// 重置所有骨骼到rest pose
    /// </summary>
    public void ResetToRestPose()
    {
        foreach (var kv in _boneRestPositions)
        {
            if (_boneCache.TryGetValue(kv.Key, out Transform t))
            {
                t.position = kv.Value;
                t.rotation = _boneRestRotations[kv.Key];
            }
        }
    }

    /// <summary>
    /// 获取动画时长
    /// </summary>
    public float GetDuration()
    {
        return _animData != null ? _animData.total_frames / _animData.fps : 0f;
    }

    /// <summary>
    /// 获取动画总帧数
    /// </summary>
    public int GetTotalFrames()
    {
        return _animData != null ? _animData.total_frames : 0;
    }

    /// <summary>
    /// 是否正在播放
    /// </summary>
    public bool IsPlaying()
    {
        return _isPlaying;
    }

    // ================================================================
    // 调试绘制
    // ================================================================

    void OnDrawGizmos()
    {
        if (!drawDebugBones || _boneCache.Count == 0) return;

        Gizmos.color = Color.green;
        foreach (var kv in _boneCache)
        {
            Gizmos.DrawWireSphere(kv.Value.position, 0.02f);
        }

        // 画脊柱线
        Gizmos.color = Color.yellow;
        string[] spineChain = { "Hips", "Spine", "Chest", "UpperChest", "Neck", "Head" };
        for (int i = 0; i < spineChain.Length - 1; i++)
        {
            if (_boneCache.TryGetValue(spineChain[i], out Transform a) &&
                _boneCache.TryGetValue(spineChain[i + 1], out Transform b))
            {
                Gizmos.DrawLine(a.position, b.position);
            }
        }

        // 画手臂线
        Gizmos.color = Color.cyan;
        DrawLimbLine("LeftUpperArm", "LeftLowerArm", "LeftHand");
        DrawLimbLine("RightUpperArm", "RightLowerArm", "RightHand");

        // 画腿线
        Gizmos.color = Color.magenta;
        DrawLimbLine("LeftUpperLeg", "LeftLowerLeg", "LeftFoot");
        DrawLimbLine("RightUpperLeg", "RightLowerLeg", "RightFoot");
    }

    private void DrawLimbLine(string upper, string lower, string hand)
    {
        if (_boneCache.TryGetValue(upper, out Transform a) &&
            _boneCache.TryGetValue(lower, out Transform b))
        {
            Gizmos.DrawLine(a.position, b.position);
        }
        if (_boneCache.TryGetValue(lower, out Transform c) &&
            _boneCache.TryGetValue(hand, out Transform d))
        {
            Gizmos.DrawLine(c.position, d.position);
        }
    }
}

