// ============================================================
// Auto-generated by SignLanguage Unity Exporter
// 医语无界 — 顶点权重平滑（Editor 脚本）
// 词条: 手术  样本: sample_手术
// 用法: 放到 Assets/Editor/ 下，选中带 SkinnedMeshRenderer 的网格后点菜单
//       「医语无界/权重/平滑选中网格顶点权重」
// ============================================================

using UnityEngine;
using UnityEditor;
using System.Collections.Generic;

public static class SignLanguageWeightSmoothing_sample_手术
{
    const int DefaultIterations = 3;

    [MenuItem("医语无界/权重/平滑选中网格顶点权重 [手术]")]
    public static void SmoothSelectedWeights()
    {
        if (Selection.activeGameObject == null)
        {
            Debug.LogWarning("[医语无界] 请先选中带 SkinnedMeshRenderer 的网格物体。");
            return;
        }
        var smr = Selection.activeGameObject.GetComponent<SkinnedMeshRenderer>();
        if (smr == null || smr.sharedMesh == null)
        {
            Debug.LogWarning("[医语无界] 选中物体缺少 SkinnedMeshRenderer 或 sharedMesh。");
            return;
        }
        SmoothWeights(smr, DefaultIterations);
    }

    static void SmoothWeights(SkinnedMeshRenderer smr, int iterations)
    {
        Mesh mesh = smr.sharedMesh;
        var weights = mesh.boneWeights;
        int vcount = mesh.vertexCount;
        if (vcount == 0 || weights == null || weights.Length == 0) return;
        int[] tris = mesh.triangles;

        // 建 1-ring 邻接表（共享边的顶点互为邻居）
        var neighbors = new List<int>[vcount];
        for (int i = 0; i < vcount; i++) neighbors[i] = new List<int>();
        for (int i = 0; i + 2 < tris.Length; i += 3)
        {
            int a = tris[i], b = tris[i + 1], c = tris[i + 2];
            neighbors[a].Add(b); neighbors[a].Add(c);
            neighbors[b].Add(a); neighbors[b].Add(c);
            neighbors[c].Add(a); neighbors[c].Add(b);
        }

        var newWeights = (BoneWeight[])weights.Clone();

        for (int it = 0; it < iterations; it++)
        {
            var src = (BoneWeight[])newWeights.Clone();
            for (int v = 0; v < vcount; v++)
            {
                var nb = neighbors[v];
                if (nb.Count == 0) continue;

                // 按骨骼聚合邻居权重（正确处理不同骨骼索引的混合）
                var boneWeightSum = new Dictionary<int, float>();
                foreach (int n in nb)
                {
                    var bw = src[n];
                    Accumulate(boneWeightSum, bw.boneIndex0, bw.weight0);
                    Accumulate(boneWeightSum, bw.boneIndex1, bw.weight1);
                    Accumulate(boneWeightSum, bw.boneIndex2, bw.weight2);
                    Accumulate(boneWeightSum, bw.boneIndex3, bw.weight3);
                }

                var sorted = new List<KeyValuePair<int, float>>(boneWeightSum);
                sorted.Sort((x, y) => y.Value.CompareTo(x.Value));

                int keep = Mathf.Min(4, sorted.Count);
                float total = 0f;
                for (int k = 0; k < keep; k++) total += sorted[k].Value;
                if (total <= 0f) continue;

                var bwOut = new BoneWeight();
                if (keep >= 1) { bwOut.boneIndex0 = sorted[0].Key; bwOut.weight0 = sorted[0].Value / total; }
                if (keep >= 2) { bwOut.boneIndex1 = sorted[1].Key; bwOut.weight1 = sorted[1].Value / total; }
                if (keep >= 3) { bwOut.boneIndex2 = sorted[2].Key; bwOut.weight2 = sorted[2].Value / total; }
                if (keep >= 4) { bwOut.boneIndex3 = sorted[3].Key; bwOut.weight3 = sorted[3].Value / total; }
                newWeights[v] = bwOut;
            }
        }

        mesh.boneWeights = newWeights;
        EditorUtility.SetDirty(mesh);
        Debug.Log($"[医语无界] 顶点权重平滑完成: {vcount} 顶点, {iterations} 次迭代。");
    }

    static void Accumulate(Dictionary<int, float> dict, int boneIndex, float weight)
    {
        if (weight <= 0f) return;
        float v;
        dict.TryGetValue(boneIndex, out v);
        dict[boneIndex] = v + weight;
    }
}
