// ============================================================
// Auto-generated by SignLanguage Unity Exporter
// 医语无界 — 动画前后对比校验（Editor 脚本）
// 词条: 用药  样本: sample_用药
// 用法: 放到 Assets/Editor/ 下，选中挂载了 SignLanguagePlayer_sample_用药 的角色后点菜单
//       「医语无界/校验/动画前后对比」
// 输出: Assets/AnimationValidation/sample_用药/ 下的 before_* 与 kf_* 截图
// ============================================================

using UnityEngine;
using UnityEditor;
using System.IO;

public static class SignLanguageAnimationValidator_sample_用药
{
    [MenuItem("医语无界/校验/动画前后对比 [用药]")]
    public static void CaptureComparison()
    {
        if (Selection.activeGameObject == null)
        {
            Debug.LogWarning("[医语无界] 请先选中挂载了 SignLanguagePlayer_sample_用药 的角色物体。");
            return;
        }

        GameObject target = Selection.activeGameObject;
        var player = target.GetComponent<SignLanguagePlayer_sample_用药>();
        if (player == null)
        {
            Debug.LogWarning("[医语无界] 选中物体上没有 SignLanguagePlayer_sample_用药 组件。");
            return;
        }

        if (!player.Initialize())
        {
            Debug.LogError("[医语无界] 动画数据初始化失败，请检查 JSON 路径。");
            return;
        }

        string outDir = Path.Combine("Assets", "AnimationValidation", "sample_用药");
        Directory.CreateDirectory(outDir);

        Bounds bounds = ComputeBounds(target);
        Camera ortho = EnsureCamera("SignLanguage_OrthoCam", true);
        Camera persp = EnsureCamera("SignLanguage_PerspCam", false);
        FrameCamera(ortho, bounds, frontOnly: true);
        FrameCamera(persp, bounds, frontOnly: false);

        // 前（rest pose）
        player.ResetToRestPose();
        Capture(ortho, Path.Combine(outDir, "before_ortho.png"));
        Capture(persp, Path.Combine(outDir, "before_persp.png"));

        // 后（每个关键帧）
        int[] keyframes = player.GetKeyframeIndices();
        foreach (int kf in keyframes)
        {
            player.ApplyFrameAt(kf);
            string tag = string.Format("kf_{0:000}", kf);
            Capture(ortho, Path.Combine(outDir, tag + "_ortho.png"));
            Capture(persp, Path.Combine(outDir, tag + "_persp.png"));
        }

        AssetDatabase.Refresh();
        Debug.Log(string.Format("[医语无界] 对比图已导出到 {0}（前 + {1} 个关键帧 × 正交/透视）。",
            outDir, keyframes.Length));
    }

    static Bounds ComputeBounds(GameObject root)
    {
        var smrs = root.GetComponentsInChildren<SkinnedMeshRenderer>(true);
        if (smrs == null || smrs.Length == 0)
            return new Bounds(root.transform.position, Vector3.one);
        Bounds b = smrs[0].bounds;
        for (int i = 1; i < smrs.Length; i++) b.Encapsulate(smrs[i].bounds);
        return b;
    }

    static Camera EnsureCamera(string name, bool orthographic)
    {
        var go = GameObject.Find(name);
        if (go == null)
        {
            go = new GameObject(name);
            go.AddComponent<Camera>();
        }
        var cam = go.GetComponent<Camera>();
        cam.orthographic = orthographic;
        return cam;
    }

    static void FrameCamera(Camera cam, Bounds b, bool frontOnly)
    {
        Vector3 center = b.center;
        float size = Mathf.Max(b.size.x, b.size.y, b.size.z);
        float dist = size * 2.5f;
        if (frontOnly)
        {
            cam.transform.position = new Vector3(center.x, center.y, center.z - dist);
            cam.orthographic = true;
            cam.orthographicSize = size * 0.9f;
        }
        else
        {
            cam.transform.position = center + new Vector3(dist * 0.6f, dist * 0.35f, -dist * 0.8f);
            cam.orthographic = false;
            cam.fieldOfView = 40f;
        }
        cam.transform.LookAt(center);
        cam.nearClipPlane = 0.01f;
        cam.farClipPlane = dist * 4f;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = new Color(0.18f, 0.18f, 0.2f, 1f);
    }

    static void Capture(Camera cam, string path)
    {
        int w = 1280, h = 960;
        var rt = new RenderTexture(w, h, 24);
        var prev = cam.targetTexture;
        cam.targetTexture = rt;
        cam.Render();
        RenderTexture.active = rt;
        var tex = new Texture2D(w, h, TextureFormat.RGB24, false);
        tex.ReadPixels(new Rect(0, 0, w, h), 0, 0);
        tex.Apply();
        cam.targetTexture = prev;
        RenderTexture.active = null;
        File.WriteAllBytes(path, tex.EncodeToPNG());
        Object.DestroyImmediate(tex);
        Object.DestroyImmediate(rt);
    }
}
