// ============================================================
// Auto-generated by SignLanguage Unity Exporter
// 医语无界 — 布料/头发物理设置（Editor 脚本）
// 词条: 咖啡  样本: sample_咖啡
// 用法: 放到 Assets/Editor/ 下，选中角色根物体后点菜单
//       「医语无界/物理/为选中角色添加布料(Cloth)」
// ============================================================

using UnityEngine;
using UnityEditor;
using System.Collections.Generic;
using System.Linq;

public static class SignLanguagePhysicsSetup_sample_咖啡
{
    // 匹配裙摆/头发/布料的关键词（按子网格名判断）
    static readonly string[] ClothKeywords =
    {
        "cloth", "skirt", "dress", "hair", "发", "裙", "衣", "披风", "裙摆", "披肩", "袖"
    };

    [MenuItem("医语无界/物理/为选中角色添加布料(Cloth) [咖啡]")]
    public static void AddClothToSelected()
    {
        GameObject target = Selection.activeGameObject;
        if (target == null)
        {
            Debug.LogWarning("[医语无界] 请先在 Hierarchy 中选中角色根物体。");
            return;
        }

        var renderers = target.GetComponentsInChildren<SkinnedMeshRenderer>(true);
        int added = 0;

        foreach (var smr in renderers)
        {
            if (smr == null) continue;
            string objName = smr.gameObject.name;
            bool isCloth = ClothKeywords.Any(k =>
                objName.IndexOf(k, System.StringComparison.OrdinalIgnoreCase) >= 0);
            if (!isCloth) continue;

            try
            {
                // Cloth 要求网格可读写(isReadable)。FBX 默认关闭 → 先检查并给明确提示
                Mesh mesh = smr.sharedMesh;
                if (mesh == null)
                {
                    Debug.LogWarning($"[医语无界] <{objName}> 没有网格(SkinnedMeshRenderer.sharedMesh 为空)，跳过。");
                    continue;
                }
                if (!mesh.isReadable)
                {
                    Debug.LogWarning($"[医语无界] <{objName}> 的网格未开启 Read/Write，无法挂 Cloth。\n"
                        + "请在 Project 中选中 FBX → Inspector 的 Model 标签 → 勾选 Read/Write Enabled → Apply。\n"
                        + "（或选中该 FBX 下的子网格资产勾选 Read/Write）。");
                    continue;
                }

                Cloth cloth = smr.GetComponent<Cloth>();
                if (cloth == null)
                {
                    cloth = smr.gameObject.AddComponent<Cloth>();
                    Undo.RegisterCreatedObjectUndo(cloth, "Add Cloth");
                }

                // 裙摆/头发调参（单位: Unity 默认米制）
                cloth.stretchingStiffness = 0.05f;   // 抗拉伸
                cloth.bendingStiffness = 0.1f;       // 抗弯折（头发可更低）
                cloth.damping = 0.8f;                // 阻尼
                cloth.useGravity = true;
                cloth.collisionMassScale = 0.5f;
                cloth.friction = 0.5f;

                added++;
                Debug.Log($"[医语无界] 已为 <{objName}> 添加 Cloth 组件。");
            }
            catch (System.Exception e)
            {
                Debug.LogError($"[医语无界] 为 <{objName}> 添加 Cloth 失败: {e.Message}");
            }
        }

        if (added == 0)
        {
            Debug.LogWarning("[医语无界] 未找到布料/头发网格。网格名需包含: " + string.Join(", ", ClothKeywords));
        }
        else
        {
            Debug.Log($"[医语无界] 完成：共 {added} 个布料网格。运行时请确保 UnityPlayer 的 enablePhysicsAfterSync 已勾选。");
        }
    }
}
